// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKdQfJVXBDRvOkkIHJK8cZA9qk6J36SXQ',
    appId: '1:391715840781:web:57e49eaf3af4000a2e4644',
    messagingSenderId: '391715840781',
    projectId: 'recette-fdf64',
    authDomain: 'recette-fdf64.firebaseapp.com',
    storageBucket: 'recette-fdf64.firebasestorage.app',
    measurementId: 'G-TFH71MD9T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1DP3Tu-ISqnIqtFeaxcqIbygDQGVMHTg',
    appId: '1:391715840781:android:c35b9b198f7e4f5a2e4644',
    messagingSenderId: '391715840781',
    projectId: 'recette-fdf64',
    storageBucket: 'recette-fdf64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoEk7J6VFiLmj41rS3clcDj0KmxOurHSI',
    appId: '1:391715840781:ios:07153b06a11dddb02e4644',
    messagingSenderId: '391715840781',
    projectId: 'recette-fdf64',
    storageBucket: 'recette-fdf64.firebasestorage.app',
    iosBundleId: 'com.example.recette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoEk7J6VFiLmj41rS3clcDj0KmxOurHSI',
    appId: '1:391715840781:ios:07153b06a11dddb02e4644',
    messagingSenderId: '391715840781',
    projectId: 'recette-fdf64',
    storageBucket: 'recette-fdf64.firebasestorage.app',
    iosBundleId: 'com.example.recette',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKdQfJVXBDRvOkkIHJK8cZA9qk6J36SXQ',
    appId: '1:391715840781:web:b59b30d60ec3f8922e4644',
    messagingSenderId: '391715840781',
    projectId: 'recette-fdf64',
    authDomain: 'recette-fdf64.firebaseapp.com',
    storageBucket: 'recette-fdf64.firebasestorage.app',
    measurementId: 'G-L7C0KCEZHW',
  );
}
